name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - name: Install dependencies
        run: |
          git clone --depth 1 https://github.com/folke/snacks.nvim \
            ~/.local/share/nvim/site/pack/packer/start/snacks.nvim

      - name: Verify plugin loads
        run: nvim --headless -c "lua require('pytest').setup()" -c "q"

